apiVersion: v1
kind: Service
metadata:
  name: {{ include "elevance-pa-assistant.fullname" . }}
  labels:
    app: {{ include "elevance-pa-assistant.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: {{ include "elevance-pa-assistant.name" . }}
